### ISSUE TITLE
Addressing the soundspaces limitation

### ISSUE THREAD

**Issue by sreeharshaparuchur1** [yyf17/SAAVN#2]
Hi,

In the readme, you mention that a focus of your work is to address the following concern: 

The volume of the target sound source is the same in all episodes of all scenes, and there is no change. The sound in the setting of SoundSpaces is acoustically clean or simple.

May I know how you verified this and the steps taken to incorporate another level of reality into the simulator and how your architecture deals with the same?

Thank You.

**Comment by yyf17** [comment]
Thank you for your attention and your question！
We started from the characteristics of SoundSpaces, and the settings we were trying to solve were acoustically complex environments.
This environment is achieved by building a sound attacker. 
The sound attacker learns to move to change position, learns to select the sound type and learns to choose the sound volume.
The acoustically complex environments are implemented by the above sound attacker.
To simplify, only consider the simplest situation, one sound attacker.
So, in our work, there are one agent and one sound attacker to play a zero-sum game.
For more details(such as algorithms and architecture), please refer to the original paper.
The specific challenges and solutions are introduced in the subsequent parts of the readme.
Since the previous description misleads you due to writing in a hurry, we have revised the content of this part, please refer to the following figure for details.
![image](https://user-images.githubusercontent.com/34536352/200718428-681dd581-879f-496e-8be8-64feabbf4dd3.png)

**Comment by sreeharshaparuchur1** [comment]
@yyf17 ,

The binaural dataset given in the soundspaces repo does not contain Binaural RIRs for all pairs of the grid points, how did you get around this limitation in your work where the agent can navigate freely in an environment?
